// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubathonManager.Data;

#nullable disable

namespace SubathonManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251021231234_separateMultiplierTypes")]
    partial class separateMultiplierTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SubathonManager.Core.Models.CssVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WidgetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WidgetId");

                    b.ToTable("CssVariables");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.MultiplierData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("ApplyToPoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApplyToSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubathonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubathonId")
                        .IsUnique();

                    b.ToTable("MultiplierDatas");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MillisecondsCumulative")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MillisecondsElapsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SubathonDatas");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Command")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MultiplierPoints")
                        .HasColumnType("REAL");

                    b.Property<double>("MultiplierSeconds")
                        .HasColumnType("REAL");

                    b.Property<int?>("PointsValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProcessedToSubathon")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SecondsValue")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("SubathonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "Source");

                    b.HasIndex("SubathonId");

                    b.ToTable("SubathonEvents");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("GoalSetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoalSetId");

                    b.ToTable("SubathonGoals");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonGoalSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SubathonGoalSets");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonValue", b =>
                {
                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Meta")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Seconds")
                        .HasColumnType("REAL");

                    b.HasKey("EventType", "Meta");

                    b.ToTable("SubathonValues");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HtmlPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.Property<int>("Z")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Widgets");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.CssVariable", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.Widget", "Widget")
                        .WithMany("CssVariables")
                        .HasForeignKey("WidgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.MultiplierData", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.SubathonData", "LinkedSubathon")
                        .WithOne("Multiplier")
                        .HasForeignKey("SubathonManager.Core.Models.MultiplierData", "SubathonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LinkedSubathon");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonEvent", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.SubathonData", "LinkedSubathon")
                        .WithMany()
                        .HasForeignKey("SubathonId");

                    b.Navigation("LinkedSubathon");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonGoal", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.SubathonGoalSet", "LinkedGoalSet")
                        .WithMany("Goals")
                        .HasForeignKey("GoalSetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LinkedGoalSet");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.Widget", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.Route", "Route")
                        .WithMany("Widgets")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.Route", b =>
                {
                    b.Navigation("Widgets");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonData", b =>
                {
                    b.Navigation("Multiplier")
                        .IsRequired();
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonGoalSet", b =>
                {
                    b.Navigation("Goals");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.Widget", b =>
                {
                    b.Navigation("CssVariables");
                });
#pragma warning restore 612, 618
        }
    }
}
