// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubathonManager.Data;

#nullable disable

namespace SubathonManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612232809_AddStateValues")]
    partial class AddStateValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("SubathonManager.Core.Models.CssVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WidgetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WidgetId");

                    b.ToTable("CssVariables");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.GoAffProStore", b =>
                {
                    b.Property<int>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RowId");

                    b.HasIndex("SiteId")
                        .IsUnique();

                    b.ToTable("GoAffProStores");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.JsVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WidgetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WidgetId");

                    b.ToTable("JsVariables");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.MultiplierData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("ApplyToPoints")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApplyToSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FromHypeTrain")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubathonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubathonId")
                        .IsUnique();

                    b.ToTable("MultiplierDatas");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.StateValue", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("StateValues");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("CapDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MillisecondsCumulative")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MillisecondsElapsed")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MoneySum")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ReversedTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SubathonDatas");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Command")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventTypeMeta")
                        .HasColumnType("TEXT");

                    b.Property<double>("MultiplierPoints")
                        .HasColumnType("REAL");

                    b.Property<double>("MultiplierSeconds")
                        .HasColumnType("REAL");

                    b.Property<int?>("PointsValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProcessedToSubathon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("SecondsValue")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("SubathonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TertiaryValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasReversed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "Source");

                    b.HasIndex("SubathonId");

                    b.ToTable("SubathonEvents");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("GoalSetId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoalSetId");

                    b.ToTable("SubathonGoals");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonGoalSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SubathonGoalSets");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<long>("CompletionDuration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FilterEventType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilterMeta")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FilterSubType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInfinite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("SubathonPrompts");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonPromptRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BaselineCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SetId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SnapshotTargetValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.HasIndex("SetId");

                    b.ToTable("SubathonPromptRuns");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonPromptSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<long>("Cooldown")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RandomOffset")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SubathonPromptSets");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonValue", b =>
                {
                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Meta")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<double>("Points")
                        .HasColumnType("REAL");

                    b.Property<double>("Seconds")
                        .HasColumnType("REAL");

                    b.HasKey("EventType", "Meta");

                    b.ToTable("SubathonValues");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.WheelItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInfinite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WheelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WheelId");

                    b.ToTable("WheelItems");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.WheelSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpinCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WheelSets");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.WheelSpinAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WheelItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WheelItemId")
                        .IsUnique();

                    b.ToTable("WheelSpinActions");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.WheelSpinHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WheelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WheelItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WheelId");

                    b.HasIndex("WheelItemId");

                    b.ToTable("WheelSpinHistories");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocsUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HtmlPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("TEXT");

                    b.Property<float>("ScaleX")
                        .HasColumnType("REAL");

                    b.Property<float>("ScaleY")
                        .HasColumnType("REAL");

                    b.Property<bool>("Visibility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.Property<int>("Z")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Widgets");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.CssVariable", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.Widget", "Widget")
                        .WithMany("CssVariables")
                        .HasForeignKey("WidgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.JsVariable", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.Widget", "Widget")
                        .WithMany("JsVariables")
                        .HasForeignKey("WidgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.MultiplierData", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.SubathonData", "LinkedSubathon")
                        .WithOne("Multiplier")
                        .HasForeignKey("SubathonManager.Core.Models.MultiplierData", "SubathonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LinkedSubathon");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonEvent", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.SubathonData", "LinkedSubathon")
                        .WithMany()
                        .HasForeignKey("SubathonId");

                    b.Navigation("LinkedSubathon");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonGoal", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.SubathonGoalSet", "LinkedGoalSet")
                        .WithMany("Goals")
                        .HasForeignKey("GoalSetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LinkedGoalSet");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonPrompt", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.SubathonPromptSet", "LinkedSet")
                        .WithMany("Prompts")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LinkedSet");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonPromptRun", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.SubathonPrompt", "LinkedPrompt")
                        .WithMany()
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubathonManager.Core.Models.SubathonPromptSet", "LinkedSet")
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LinkedPrompt");

                    b.Navigation("LinkedSet");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.WheelItem", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.WheelSet", "LinkedWheel")
                        .WithMany("WheelItems")
                        .HasForeignKey("WheelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LinkedWheel");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.WheelSpinAction", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.WheelItem", "LinkedItem")
                        .WithOne("Action")
                        .HasForeignKey("SubathonManager.Core.Models.WheelSpinAction", "WheelItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedItem");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.WheelSpinHistory", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.WheelSet", "LinkedWheel")
                        .WithMany()
                        .HasForeignKey("WheelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SubathonManager.Core.Models.WheelItem", "LinkedItem")
                        .WithMany()
                        .HasForeignKey("WheelItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedItem");

                    b.Navigation("LinkedWheel");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.Widget", b =>
                {
                    b.HasOne("SubathonManager.Core.Models.Route", "Route")
                        .WithMany("Widgets")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.Route", b =>
                {
                    b.Navigation("Widgets");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonData", b =>
                {
                    b.Navigation("Multiplier")
                        .IsRequired();
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonGoalSet", b =>
                {
                    b.Navigation("Goals");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.SubathonPromptSet", b =>
                {
                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.WheelItem", b =>
                {
                    b.Navigation("Action");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.WheelSet", b =>
                {
                    b.Navigation("WheelItems");
                });

            modelBuilder.Entity("SubathonManager.Core.Models.Widget", b =>
                {
                    b.Navigation("CssVariables");

                    b.Navigation("JsVariables");
                });
#pragma warning restore 612, 618
        }
    }
}
